USE imagedetection;

SET FOREIGN_KEY_CHECKS=0; DROP TABLE images; SET FOREIGN_KEY_CHECKS=1;
SET FOREIGN_KEY_CHECKS=0; DROP TABLE tags; SET FOREIGN_KEY_CHECKS=1;

DROP TABLE IF EXISTS imageTags;

ALTER TABLE images DROP FOREIGN KEY FK21f4xbrqud8fwi845gh5n9b6n;

DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS images;
CREATE TABLE images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(255)
)ENGINE=InnoDB;

CREATE TABLE tags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(255)
)ENGINE=InnoDB;